import { Link } from "react-router-dom";

function EcocoLogo({ size = 36 }: { size?: number }) {
  return (
    <Link to="/" className="flex items-center gap-2 no-underline">
      <svg viewBox="0 0 100 110" width={size} height={Math.round(size * 1.1)} fill="none" xmlns="http://www.w3.org/2000/svg">
        <rect x="46" y="4" width="8" height="16" rx="4" fill="#2a6632" />
        <path d="M50 14 Q68 4 84 14 Q72 20 56 18 Q53 16 50 14Z" fill="#2a6632" />
        <ellipse cx="50" cy="56" rx="40" ry="36" fill="#2a6632" />
        <text x="50" y="53" textAnchor="middle" dominantBaseline="central"
          fontFamily="Syne, sans-serif" fontWeight="800" fontSize="56"
          textLength="40" lengthAdjust="spacingAndGlyphs"
          fill="#f0f7ee">e</text>
      </svg>
      <span style={{ fontFamily: "'Syne', sans-serif", fontWeight: 800, fontSize: size > 28 ? 22 : 16, letterSpacing: '-0.03em', color: '#2a6632', lineHeight: 1 }}>
        ECoCo
      </span>
    </Link>
  );
}

export default function Home() {
  return (
    <div className="min-h-screen flex flex-col" style={{ fontFamily: "'DM Sans', sans-serif" }}>
      {/* Hero Section */}
      <section className="flex-1 flex flex-col bg-gradient-to-b from-[#7aaa7a] to-ecoco-light">
        {/* Navigation */}
        <nav className="flex items-center justify-between px-6 py-4">
          <EcocoLogo size={36} />
          <div className="flex gap-6">
            <Link to="/" className="text-sm font-medium text-ecoco-black hover:underline">Home</Link>
            <Link to="/evaluate" className="text-sm font-medium text-ecoco-black hover:underline">Evaluate</Link>
          </div>
        </nav>

        {/* Hero Content */}
        <div className="flex-1 flex flex-col items-center justify-center px-6 py-10">
          <h1 className="text-6xl font-bold text-center mb-2 text-ecoco-black" style={{ fontFamily: "'Syne', sans-serif" }}>
            ECoCo
          </h1>
          <h2 className="text-2xl font-medium text-center mb-4 max-w-2xl text-ecoco-dark" style={{ fontFamily: "'DM Sans', sans-serif" }}>
            Exploring Confidence and Consistency in SQL Queries Generated by Large Language Models
          </h2>
          <p className="text-base text-ecoco-black/70 mb-5">
            Feed your own tables, test with your own data, evaluate what you want
          </p>
          <Link
            to="/evaluate"
            className="bg-ecoco-dark text-ecoco-light px-6 py-3 rounded hover:bg-ecoco-black transition font-medium"
          >
            • Explore the Tool
          </Link>
        </div>
      </section>

      {/* Preview Image Section */}
      <section className="bg-ecoco-black py-10 px-6">
        <div className="max-w-5xl mx-auto">
          <div className="bg-white rounded-lg overflow-hidden shadow-2xl">
            <img src="/tool_screenshot.png" alt="Tool Preview" className="w-full h-auto" />
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-ecoco-mid py-4 px-6">
        <div className="flex items-center justify-between">
          <EcocoLogo size={24} />
          <div className="flex gap-6">
            <Link to="/" className="text-sm font-medium text-ecoco-dark hover:underline">Home</Link>
            <Link to="/evaluate" className="text-sm font-medium text-ecoco-dark hover:underline">Evaluate</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
